### ISSUE TITLE
Where's the source code?

### ISSUE THREAD

**Issue by johnnyontheweb** [OpenSeesforFire/openseesforfire.github.io#17]
In html download page, there's witten:

> To browse our version of source code, you could simply go to our Github page

Where's the source code here on github?
I cannot find it anywhere.

**Comment by LimingXLiming** [comment]
Hi, it is in the code page and you need to change the branch to SRC

**Comment by johnnyontheweb** [comment]
Thanks for your reply. I suggest that it must be specified in the web site, it is unusual to store code outside "master" branch.
