### ISSUE TITLE
How does FiberSection2dThermal calculate moment?

### ISSUE THREAD

**Issue by mcoar** [OpenSeesforFire/openseesforfire.github.io#18]
Good morning, 
I am curious about the moment calculation that is used by the FiberSection2dThermal section. I have pasted a section from Elhami Khorasani et al 2015 about how the OpenSees Thermal module calculates moment, and the "double-counting" of modulus reduction for thermal fibers at elevated temperatures in the equations for Fth and zbar. The results from my validation suggest that the current OpenSees version 3.2.0 uses the _effective_ centroid zbar = \sum{Ar*Er*zr}/\sum{Ar*Er}, when my understanding is that it should use the _geometric centroid_ zbar = \sum{Ar*zr}/\sum{Ar} for calculating thermal moment. 

I am not quite familiar enough with C++ to understand from the code itself how these values are calculated. Any support in whether this change has been implemented, or if not, why not, would be appreciated. Thank you!

![image](https://user-images.githubusercontent.com/53275798/80818094-9f306a80-8ba0-11ea-91f2-6090d15834cc.png)
![image](https://user-images.githubusercontent.com/53275798/80818128-a9526900-8ba0-11ea-83f3-d9618ffe9f81.png)
[Khorasani, Garlock, Quiel - 2015 - Modeling steel structures in OpenSees Enhancements for fire and multi-hazard probabilistic analyses.pdf](https://github.com/OpenSeesforFire/openseesforfire.github.io/files/4565018/Khorasani.Garlock.Quiel.-.2015.-.Modeling.steel.structures.in.OpenSees.Enhancements.for.fire.and.multi-hazard.probabilistic.analyses.pdf)

**Comment by LimingXLiming** [comment]
Hi,

Sorry for the much delayed reply.

The updated OpenSees does use the effective centroid for fibres, and for thermal moment it is actually not so important because in the later iterations it is only necessary to count the thermal strain in the calculation of mechanical strain at each load step.

Regards,
Liming
