### ISSUE TITLE
the output file is generating with 0kb 

### ISSUE THREAD

**Issue by ChilupuriTejaswini** [OpenSeesforFire/openseesforfire.github.io#23]
I'm working in openseesforfire but when a example code is executed it is generating output file with zero kb file.I don't understand where i was making wrong.

**Comment by Tenghankai** [comment]
Do you find the solution?

**Comment by ChilupuriTejaswini** [comment]
yes, i found the solution

**Comment by Tenghankai** [comment]
Could you tell me why this problem arise？

**Comment by ChilupuriTejaswini** [comment]
I have not created opensees.bat file and I suggest some videos should be
available for understanding of openseesforfire scripting of fire
